const LOAD_SOURCES = "LOAD_SOURCES";
const RECIEVE_SOURCES = "RECIEVE_SOURCES";
const REJECT_SOURCES = "REJECT_SOURCES";
const RECIEVE_DATED_SOURCES = "RECIEVE_DATED_SOURCES";

const ADD_FILTER = "ADD_FILTER";
const REMOVE_FILTER = "REMOVE_FILTER";
const SET_FILTERS = "SET_FILTERS";

const RECIEVE_CATEGORIES = "RECIEVE_CATEGORIES";
const LOAD_CATEGORIES = "LOAD_CATEGORIES";
const REJECT_CATEGORIES = "REJECT_CATEGORIES";

const RECIEVE_COUNTRIES = "RECIEVE_COUNTRIES";
const LOAD_COUNTRIES = "LOAD_COUNTRIES";
const REJECT_COUNTRIES = "REJECT_COUNTRIES";

const FILTER_SOURCES = "FILTER_SOURCES";



export {
  LOAD_SOURCES,
  RECIEVE_SOURCES,
  REJECT_SOURCES,
  RECIEVE_DATED_SOURCES,

  ADD_FILTER,
  REMOVE_FILTER,
  SET_FILTERS,

  RECIEVE_CATEGORIES,
  LOAD_CATEGORIES,
  REJECT_CATEGORIES,

  RECIEVE_COUNTRIES,
  LOAD_COUNTRIES,
  REJECT_COUNTRIES,

  FILTER_SOURCES
};
